### ISSUE TITLE
Errors using the ImagePredictor

### ISSUE THREAD

**Issue by ClemPalf** [awslabs/autogluon#1474]
Hi,

I am trying to use the ImagePredictor within a Sagemaker studio instance (ml.m5.large with a MXnet 1.8 Python 3.7 CPU Optimized kernel).

Following closely the "Image Prediction - Search Space and Hyperparameter Optimization (HPO)" tutorial, I still face errors I can't figure out.

With the following code: 
`model = ag.Categorical('coat_tiny', 'inception_v4', 'resnet18', 'resnet26', 'vgg16')`
`lr = ag.Real(0.001, 0.1, log=True)`
`batch_size = ag.Categorical(32, 64, 128, 256)`

`hyperparameters = {'model': model, 'batch_size': batch_size, 'lr': lr, 'epochs': 3}`
`predictor = ImagePredictor()`
`predictor.fit(dataset, time_limit=60*120, hyperparameters=hyperparameters,
                    hyperparameter_tune_kwargs={'searcher': 'bayesopt', 'num_trials': 2})` 

I get: " ValueError: Active hyperparameter 'batch_size▁choice' not specified! " 

Also, if I don't specify the "searcher" parameter, I get: " KeyError: 'estimator' ".

Here is my notebook if you want to have a closer look the error messages: 
https://github.com/ClemPalf/SageMaker-Inventory-monitoring/blob/main/2)%20Model_choice_with_autogluon.ipynb

Is there something obvious I am missing? 

Kind regards,

Clem

**Comment by Innixma** [comment]
I believe this bug has been fixed in pre-release/upcoming v0.4 due to a refactor of the HPO backend.

Can you try again after installing via pre-release:

```
pip install --pre autogluon
```

One edit you will have to make is that bayesopt is no longer support at the moment. The searcher bug has also been fixed. Instead simply do:

```
predictor.fit(dataset, time_limit=60*120, hyperparameters=hyperparameters, hyperparameter_tune_kwargs={'num_trials': 2})
```

The other problem you might face is that you are training on a CPU instance. This is not a good idea, and you should consider using a GPU instance with CUDA when training image models. Otherwise it might be very slow or not work at all.

**Comment by ClemPalf** [comment]
Hello Innixma,

I tried with the pre-release version and by getting rid of the searcher parameter, unfortunately I still get the "KeyError: 'estimator'" error. Here is my updated notebook: https://github.com/ClemPalf/SageMaker-Inventory-monitoring/blob/main/2)%20Model_choice_with_autogluon.ipynb

Cheers, 

Clem

Ps: I tried with GPU-equipped instances but always ended up with workers from the data logger dying due to insufficient shared memory (I was using a ml.g4dn.xlarge). Do you have any tips on how to raise the shared memory limit on sagemaker notebook instances?
