### ISSUE TITLE
I had some problems running the Object Detection - Quick Start sample

### ISSUE THREAD

**Issue by Fan-tas-tic** [awslabs/autogluon#1521]
when i run these codes:

time_limit = 60*30  # at most 0.5 hour
detector = ObjectDetector()
hyperparameters = {'epochs': 5, 'batch_size': 8}
hyperparameter_tune_kwargs={'num_trials': 2}     detector.fit(dataset_train,time_limit=time_limit,hyperparameters=hyperparameters,hyperparameter_tune_kwargs=hyperparameter_tune_kwargs)

errors:
Exception during a trial: type object 'SSDEstimator' has no attribute '_default_cfg'
Exception during a trial: type object 'YOLOv3Estimator' has no attribute '_default_cfg'
Exception during a trial: type object 'SSDEstimator' has no attribute '_default_cfg'
KeyError: 'map_reward'

**Comment by Fan-tas-tic** [comment]
sorry,i find the reason,that forget !pip install -U "mxnet<2.0.0"

**Comment by zz-xx** [comment]
@Innixma I'm facing this very same issue on Windows 11 while running Object Detection - Quick Start example. I have correct pytorch setup with CUDA and didn't installed mxnet as suggested in documentation (for Windows). Can you please point to me what I'm missing? 

Since this seems like mxnet issue, afterwards I tried installing mxnet (CPU) for Windows but there are some dependency version conflicts so it didn't work for me.  If you can point me to some instructions for making pytorch+GPU work on Windows 11 for autogluon.vision it will be very helpful.

Thank you.

**Comment by Innixma** [comment]
@zz-xx currently object detection is not supported on Windows as it only works with MXNet (and MXNet doesn't work on Windows). We are planning to add Torch support in future releases (possibly v0.5), but this is not yet available.

**Comment by zz-xx** [comment]
Thank you for confirming this. 

I managed to run object detection quick start sample and train my own model using mxnet (CPU) on Windows. Since this is not officially supported, there are lot of dependency version conflicts to navigate. If there's interest, I can document my steps.

**Comment by Innixma** [comment]
@zz-xx if you'd like to provide the steps to assist future windows users who are searching this issue, that could be helpful. It may be best for us to simply add a warning that OD is not supported on Windows though, as training OD models on CPU isn't very helpful beyond toy examples.

**Comment by HaithemH** [comment]
> 

Running the Quickstart example on Colab, I faced the same error.:  KeyError: 'map_reward'.
By installing mxnet<2.0.0 the problem is solved.
Thank you for sharing

**Comment by For-Chance** [comment]
Running the Quickstart example on Colab, and I faced the same error.: KeyError: 'map_reward'.
Even thought installing mxnet<2.0.0, the problem is still not solved. So what can I do next?
mxnet: 1.9.0
autogluon: 0.5.0

**Comment by nanodust** [comment]
same as @For-Chance  - I've used tabular but this is my first time using objectdetector. 

I know my ObjectDetector.Dataset is happy, can show_images() and view bboxes.

yet following along the [quickstart doc](https://auto.gluon.ai/stable/tutorials/object_detection/beginner.html),  there appears to be an issue 

```
time_limit = 60*30  # at most 0.5 hour
detector = ObjectDetector()
hyperparameters = {'epochs': 5, 'batch_size': 8}
hyperparameter_tune_kwargs={'num_trials': 2}
detector.fit(dataset, time_limit=time_limit, hyperparameters=hyperparameters, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs)
```
errors out with 

```
ERROR: Exception during a trial: type object 'SSDEstimator' has no attribute '_default_cfg'
ERROR: Exception during a trial: type object 'YOLOv3Estimator' has no attribute '_default_cfg'
ERROR: Exception during a trial: type object 'SSDEstimator' has no attribute '_default_cfg'
... 
KeyError: 'map_reward'
```
if helpful, see [full trace](https://pastebin.com/QX0NpRJs)

mxnet: 1.9.1
autogluon: 0.5.2

any ideas ? 

If i figure it out, will update here. 

thanks !!

**Comment by nanodust** [comment]
I was able to get the quickstart working by installing from source per [doc](https://auto.gluon.ai/stable/install.html)

```
!python3 -m pip install "mxnet<2.0.0, >=1.7.0"
!python3 -m pip install torch==1.12.0+cpu torchvision==0.13.0+cpu torchtext==0.13.0 --extra-index-url https://download.pytorch.org/whl/cpu
! git clone https://github.com/awslabs/autogluon
!cd autogluon && ./full_install.sh
```

then was able to proceed w/ fit , etc as expected
