### ISSUE TITLE
ImportError: cannot import name 'TabularPrediction' from 'autogluon' (/home/tommaso/repos/gemintelligence/env/lib/python3.7/site-packages/autogluon/__init__.py)

### ISSUE THREAD

**Issue by TommasoBendinelli** [awslabs/autogluon#811]
I am getting this error with a fresh install using the commands in the home page

```
# Here we assume CUDA 10.1 is installed.  You should change the number
# according to your own CUDA version (e.g. mxnet_cu100 for CUDA 10.0).
python3 -m pip install --upgrade "mxnet_cu101<2.0.0"
python3 -m pip install autogluon
```

And then 
```
from autogluon import TabularPrediction as task
```

**Comment by trunghlt** [comment]
This has been blocking our releases too.

**Comment by bhithesh** [comment]
Any suggestion on alternative

**Comment by Innixma** [comment]
I have reproduced the issue on a fresh machine and will deep dive:

```
>>> from autogluon import TabularPrediction as task
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TabularPrediction' from 'autogluon' (/home/ubuntu/virtual/autogluon_test/lib/python3.7/site-packages/autogluon/__init__.py)
```

**Comment by Innixma** [comment]
Issue identified:

`gluoncv` recently released v0.9.0 which depends on the pre-release `autogluon.core` module. AutoGluon has been changed to be a namespace package in preparation for v0.1 release, meaning it is now made up of several separate packages. However, having both `autogluon==0.0.14` (non-namespace) and `autogluon.core` (namespace) installed creates a namespace collision. Because `autogluon==0.0.14` installs `'gluoncv>=0.5.0,<1.0',`, it installs the new `gluoncv==0.9.0` which creates the namespace collision and breaks the package.

The following installation process works:

```
# Optionally upgrade pip for faster install and newer mxnet version
python3 -m pip install --upgrade pip

python3 -m pip install "mxnet<2.0.0"
python3 -m pip install "gluoncv>=0.5.0,<0.9.0"
python3 -m pip install autogluon
```

To fix a pre-existing broken environment:

```
python3 -m pip uninstall autogluon.core
python3 -m pip uninstall autogluon
python3 -m pip uninstall gluoncv
python3 -m pip install "gluoncv>=0.5.0,<0.9.0"
python3 -m pip install autogluon
```

**Comment by Innixma** [comment]
This issue has been fixed with the release of [v0.0.15](https://github.com/awslabs/autogluon/releases/tag/v0.0.15). Please install the new version from a fresh environment to avoid any corruptions from prior installs. v0.0.15 should work identically to v0.0.14 minus the installation issue.

**Comment by jesteria** [comment]
I can confirm this is resolved by `v0.0.15`.

**Comment by RuojiWang** [comment]
This is the problem that bothered me for a few days. Now the problem is solved, thanks a lot :)

**Comment by Patrickbro13** [comment]
That issue is still there @Innixma 
https://colab.research.google.com/drive/1JeK6zFR78fgYklaoyJbsE04mEjrPnWVC?usp=sharing#scrollTo=sIPK7XQJQmzo

**Comment by Innixma** [comment]
@Patrickbro13 

> That issue is still there @Innixma
> https://colab.research.google.com/drive/1JeK6zFR78fgYklaoyJbsE04mEjrPnWVC?usp=sharing#scrollTo=sIPK7XQJQmzo

This notebook is installing a pre-release version of AutoGluon from 2020 and the error you are getting in the notebook is unrelated to this GitHub issue, and is a parsing error by the user that did not convert their dtypes to float.

**Comment by Patrickbro13** [comment]
@Innixma I am really sorry , I forgot to update the issue and the link to the older notebook file which had that issue where I was installing the autogluon with the above instructions as mentioned but I found another notebook of your in other issue which resolved the issue so thanks for that and you can close this issue 😄
